name: Keep Backend Alive

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl "https://clicandrun.onrender.com/competition?page=0&size=1"
